version: '3.8'

services:
  api:
    build:
      context: ./server
    ports:
      - 3001:3001
    environment:
      REDIS_URL: redis://:dev_pass@redis:6379/0
      PORT: 3011
      METHOD: POST
    depends_on:
      - redis

  redis:
    image: 'redis:7-alpine'
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: dev_pass
    volumes:
      - redis_data:/data

  cpanel:
    build:
      context: ./cpanel
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: file:/db/database.db
      REDIS_URL: redis://:dev_pass@redis:6379/0
    volumes:
      - sqlite:/db
    depends_on:
      - redis

volumes:
  redis_data:
    name: 'RedisVolume'

  sqlite:
    name: 'SQLite'
