// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type TextRequestInput struct {
	FileName string      `json:"fileName"`
	Payload  interface{} `json:"payload,omitempty"`
}
